version: '3.9'

services:
  mongodb:
    container_name: mongodb
    restart: always
    env_file:
      - .env
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./volumes/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      #- MONGO_INITDB_DATABASE=my_db
